version: '3.4'

services:
  postgres:
    container_name: todo-graphql
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:  
      POSTGRES_USER: puru2905
      POSTGRES_DB: todo-graphql
      POSTGRES_PASSWORD: todo
volumes:
  postgres_data: